[package]
name = "shoplocal-admin"
version = "0.1.0"
authors = ["natem"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
mongodb = "1.1.1"
dotenv = "0.15.0"